### ISSUE TITLE
Unable to deserialize Stripe API yaml

### ISSUE THREAD

**Issue by jtk18** [glademiller/openapiv3#15]
`rustc 1.39.0 (4560ea788 2019-11-04)`
`openapiv3 = "0.3.0"`

Hello! It seems there's an issue with deserializing some paths. I'm attempting to deserialize the Stripe API OpenAPI yaml found [here](https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.sdk.yaml).

My simple test program looks like:
```rust
use serde_yaml;
use openapiv3::OpenAPI;

fn main() {
    let data = include_str!("../spec3.sdk.yaml");
    let openapi: OpenAPI = serde_yaml::from_str(data).expect("Could not deserialize input");
    println!("{:?}", openapi);
}
```

And I'm getting the following error:
```
thread 'main' panicked at 'Could not deserialize input: Message("data did not match any variant of untagged enum ReferenceOr", Some(Pos { marker: Marker { index: 731702, line: 21072, col: 17 }, path: "paths" }))', src/libcore/result.rs:1165:5
```

The text indicated by the marker in that output is at the following section of the file:
```
paths:
  "/v1/3d_secure":
```
The line is the quoted path `"/v1/3d_secure":` and the column is the second 'e' right before the quote. 

Any help in debugging this would be appreciated. Is there anything else I can provide?

Thank you!

**Comment by glademiller** [comment]
Thanks for the report.

**Comment by jtk18** [comment]
Thank you for the fix and the test!
