### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by JordiPolo** [glademiller/openapiv3#19]
I believe [extensions of Openapi v3](https://swagger.io/docs/specification/openapi-extensions/) would just not be represented in the structures so they get lost in the deserialization of the document.

I suppose that this would need to be supported as some kind of map as there is no way of knowing beforehand the keys.

**Comment by omallassi** [comment]
This would be awesome to support extensions. I typically have a case where the `audience` has been defined as an extension

```
openapi: 3.0.0
info:
  x-audience: company
  title: 
```

**Comment by JordiPolo** [comment]
I have all type of use-cases, one big one is defining performance information, I'm sure multiple people will have their own

**Comment by ahl** [comment]
@glademiller if you'd potentially accept a PR for this issue, I'd happily submit one.
