### ISSUE TITLE
Release 0.3.2 breaks compat with 0.3.0

### ISSUE THREAD

**Issue by mzabaluev** [glademiller/openapiv3#20]
I get a breakage after `cargo update` which updated 0.3.0 to 0.3.2:

```
error[E0063]: missing fields `max_length`, `min_length` in initializer of `openapiv3::StringType`
   --> jcli/src/jcli_app/utils/open_api_verifier.rs:398:59
    |
398 |     let valid_schema_kind = SchemaKind::Type(Type::String(StringType {
    |                                                           ^^^^^^^^^^ missing `max_length`, `min_length`
```

The dependency is listed as `openapiv3 = "0.3.0"`. Cargo has rather looser conventions than standard semver on what versions are considered compatible for `^0.x.y`. To avoid unexpected breakage for crate registry users, it's better to increment the minor version also in 0.x when introducing breaking changes.

**Comment by glademiller** [comment]
Apologies for the breaking change on that. I didn't think enough about the Pull requests I merged to realize they were backward incompatible. I will be more careful going forward.

**Comment by JordiPolo** [comment]
Oops, my fault, I did not think about match being exhaustive and thus that even adding properties to an struct is backwards compatible?

**Comment by ahl** [comment]
I'm not sure that there's a fix here other than to suggest liberal use of `Default::default()` to protect against new fields. That said, this seems like an omission unlikely to be repeated.
