### ISSUE TITLE
Release 0.3.3 breaks compat with 0.3.2

### ISSUE THREAD

**Issue by msrd0** [glademiller/openapiv3#26]
Just like you realized last release (#20), adding fields to a struct when all fields are public is a breaking change. The following code compiles with 0.3.2 but fails to compile with 0.3.3:

```rust
use openapiv3::Info;

fn main() {
        let api_info = Info {
                title: "Test".to_owned(),
                description: Some("Test Specification".to_owned()),
                terms_of_service: None,
                contact: None,
                license: None,
                version: "0.0.0".to_owned()
        };
}
```

Maybe next time you need to change your test code because it fails to compile, consider it a warning sign that your changes are indeed breaking changes: https://github.com/glademiller/openapiv3/commit/1e009b2ee30f7f86831c5742e72f98bbb0c9a875#diff-a7301f9a3dcd2e25ff77be69aa773585260086ada5c48a4b87c512aca41b1ba6R91

**Comment by ahl** [comment]
Indeed this was a breaking change @msrd0. I should have bumped the version number to 0.4.0, I believe. Hopefully you'll take the same step as in the diff you found to make use of Default::default().

Is there some remediation you'd suggest at this point or are you filing an issue merely to note the error?

**Comment by msrd0** [comment]
I opened this issue just to notify you of your error - I've changed my version requirement to `=0.3.2` to avoid any more suprises like this.

The most correct action would of course be to yank 0.3.3 and re-publish it as 0.4.0, but I'll leave it up to you if you take this step or not.

**Comment by ahl** [comment]
done
