### ISSUE TITLE
Parameter style

### ISSUE THREAD

**Issue by tiagolobocastro** [glademiller/openapiv3#27]
Hi,

First of all massive thanks for this project! I'm converting openapiv2 to openapiv3 on a project and I really enjoyed using this implementation with a less ambiguity than the v2 I'm using which makes things easier :)

A couple of questions, on the `Parameter` could the `style` deserialize be skipped if it's at it's default value, or maybe could be made an Option? From the spec: "Default values (based on value of in): for query - form; for path - simple; for header - simple; for cookie - form."

Thanks!

**Comment by tiagolobocastro** [comment]
Also could add some of the other string formats: https://swagger.io/docs/specification/data-models/data-types/#string, eg uuid, hostnamet, etc..

**Comment by tiagolobocastro** [comment]
Raised #28 to address the formats and the style.

**Comment by ahl** [comment]
Yeah, I think they could be skipped, but in-general being explicit seems preferable to relying on implicit defaults. What would you think about a crate feature for this functionality? It could use `#[serde(skip_serializing_if = ...)]`.

**Comment by tiagolobocastro** [comment]
> Yeah, I think they could be skipped, but in-general being explicit seems preferable to relying on implicit defaults. What would you think about a crate feature for this functionality? It could use `#[serde(skip_serializing_if = ...)]`.

That seems reasonable, any suggestions for the feature name? "skip_serializing_defaults" ?

**Comment by ahl** [comment]
A little verbose, but no one's going to get confused. I like it!

**Comment by tiagolobocastro** [comment]
Thanks, I've updated #28 with the feature.

I'm wondering about the format... on the spec it says: "However, format is an open value, so you can use any formats, even not those defined by the OpenAPI Specification, such as:  .... and others"

If it's open, would it make sense to have the Other take a String? `Other(String)` and when serializing we'd deserialize the String? And so we would not have to update the format again?

**Comment by tiagolobocastro** [comment]
Fixed by #28
