### ISSUE TITLE
How to set parameter default value

### ISSUE THREAD

**Issue by PrivateRookie** [glademiller/openapiv3#35]
According to openapiv3 [parameter spec](https://swagger.io/docs/specification/describing-parameters/), a parameter default value can be set by `default` field , but I can't find relative field in SchemaKind struct, how to describe a default value in parameter in openapiv3 crate?

**Comment by ahl** [comment]
I think what you're looking for is in `SchemaData`:
https://docs.rs/openapiv3/0.5.0/openapiv3/struct.SchemaData.html#structfield.default

**Comment by ahl** [comment]
Closing this. Feel free to re-open if this didn't address your issue.
