### ISSUE TITLE
Automatic resolution of `$ref`s

### ISSUE THREAD

**Issue by JamesHinshelwood** [glademiller/openapiv3#37]
It might be useful for this library to have the ability of resolving `$ref`s. We may want to stop short of making network requests to resolve external documents, but it might be possible to provide an API which allows users to resolve local `$ref`s? I'm not entirely sure what this API should look like though. Obviously an `OpenAPI` doesn't currently know where it lives on disk (if it even does), so there is no immediate way to decide where to resolve paths from. We could add a function to `ReferenceOr` which takes a `root_dir` parameter and resolves it's reference from there?

**Comment by ahl** [comment]
That sounds interesting; what is your use case?

**Comment by JamesHinshelwood** [comment]
@ahl I'm auto-generating Rust clients for my APIs using this library and [quote](https://docs.rs/quote/1.0.9/quote/). My openapi specification is split across multiple local files (using `$ref`s like `"foo.yaml#/items/bar"`).

My current solution is shelling out to [`openapi-cli`](https://github.com/Redocly/openapi-cli) and using it's `bundle` function to pre-process my specification before passing it to this library. This ensures the only `$ref`s that remain are to objects in the same definition.

However, doing this bundling out-of-process makes the dependencies for my build script fairly complicated (it needs to depend on `node` being installed) so I would much prefer an in-process solution which lets me solve this in Rust.

One way I imagined this might work is something like (please forgive the psuedo-code):

```rust
impl ReferenceOr {
    fn resolve(&self, root_dir: &Path) -> ReferenceOr {
        match self {
            ReferenceOr::Item(_) => self,
            ReferenceOr::Reference { reference } => {
                // Parse the `reference` properly based on whatever the spec. says. Not like this :)
                let parts = reference.split('#');

                let file = root_dir.join(parts[0]);
                let file = "...";// read the file
                let inner_api = OpenApi::from_str(&file);
                
                ReferenceOr::Item(inner_api.get(parts[1]))
            }
        }
    }
}
```

This strikes me as a bit of an ugly API so I'd happily discuss other ideas.

**Comment by JamesHinshelwood** [comment]
Ah I've just realised that doesn't really solve the problem. Because when you resolve an item from another file, that might contain a `$ref` to another local object in that same file which you've now lost the link to.

Maybe it is easiest to continue with a separate external (but maybe re-written in Rust :) ) openapi bundler rather than trying to be smart in this library.
