### ISSUE TITLE
Links with just an operation_ref fail to deserialise

### ISSUE THREAD

**Issue by rbtcollins** [glademiller/openapiv3#39]
This minimal example fails to parse with serde_json::from_$
```
"{\"openapi\":\"\",\"info\":{\"title\":\"\",\"version\":\"\"},\"paths\":{\"\":{\"trace\":{\"responses\":{\"100\":{\"description\":\"\",\"links\":{\"\":{\"operation_ref\":\"\"}}}}}}}}"
```

This parses:
```
"{\"openapi\":\"\",\"info\":{\"title\":\"\",\"version\":\"\"},\"paths\":{\"\":{\"trace\":{\"responses\":{\"100\":{\"description\":\"\",\"links\":{\"\":{\"operation_ref\":\"\",\"parameters\":{}}}}}}}}}"
```

I've been doing proptest generation of schemas to test some logic built on this which is how I discovered the behaviour. I would argue that it is a genuine bug since the spec makes every field in Link optional.

Relatedly, I model  the ref/id pair as an Enum, so that proptest knows to generate one of them always : and I'd argue that modelling it as an Enum in opeapiv3 would be better too, but I'm not sure that would help serde figure out whats present when parameters is not present in the doc.

**Comment by ahl** [comment]
I discovered this as well the other day. I'll have a fix in very soon and I'll cut a new release.

**Comment by ahl** [comment]
I like the suggestion of making `operation_ref` and `operation_id` into an `enum`
