### ISSUE TITLE
`ArrayType.items` shouldn't be `Option<...>`

### ISSUE THREAD

**Issue by dlowe** [glademiller/openapiv3#56]
This change: https://github.com/glademiller/openapiv3/commit/1eda5d6edbd20e8bdf2f9bb396040db2d913c48e looks wrong to me.

The [openapi spec](https://swagger.io/specification/), under "Schema Object" -> "Properties" says:

> items - ... items MUST be present if the type is array.

What was the reason for the change?

**Comment by ahl** [comment]
I agree. This is an area where, unfortunately, where the JSON Schema defined by the OpenAPI maintainers doesn't match the language of the actual spec.

https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.yaml

While the OpenAPI TSC says this is not the source of truth, the *de facto* spec is what tools generate and linters enforce. Consequently, tooling doesn't validate this and some common API descriptions omit the `items` field. In particular:

https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json

```
$ jq '..|select(.type? == "array") | select(has("items")==false)' api.github.com.json
{
  "type": "array"
}
{
  "type": "array"
}
{
  "type": "array"
}
{
  "type": "array"
}
{
  "type": "array"
}
{
  "type": "array"
}
{
  "type": "array"
}
{
  "type": "array",
  "description": "Array of the domain set and its alternate name (if it is configured)",
  "example": [
    "example.com",
    "www.example.com"
  ]
}
```

The reason for the change was to be able to easily process files that tools produce and linters  validate even when those files don't obey the OpenAPI 3.0.3 spec.

**Comment by dlowe** [comment]
That's frustrating, but makes sense. Thanks for explaining!

Tangentially, then: any idea how a spec consumer is supposed to *interpret* the case where `array.items.is_none()`? Treat it as `schema: {}`?

**Comment by ahl** [comment]
It's not the world's strongest explanation, but I think it's preferable for a crate like this roll with the punches rather than to insist on strict adherence to the spec. Yes, I think that's the right way to handle this scenario based on the relevant JSON Schema draft:

> if "items" is not present, or its value is an object, validation of the instance always succeeds, regardless of the value of "additionalItems";

To briefly add some commentary, this is some of the trouble with the OpenAPI 3.0.x decision to use a JSON Schema with additions and subtractions approach. The 3.1 approach of adoption JSON Schema with a few small extensions is much more rational.

**Comment by dlowe** [comment]
Understood. Thanks so much for hashing it out with me :)
