### ISSUE TITLE
Some vectors contain Option<?>

### ISSUE THREAD

**Issue by CatDevz** [glademiller/openapiv3#59]
Some vectors such as `StringType::enumeration` are defined as `Vec<Option<String>>`, why have a list of potential strings?

**Comment by ahl** [comment]
Yeah, weird, right? Consider this schema:

```json
{
    "type": "string",
    "nullable": true,
    "enum": ["yes", "no", null]
}
```

It's an `Option<String>` to handle that case.

**Comment by CatDevz** [comment]
> Collaborator
> ### ** [ahl](/ahl) ** commented [5 hours ago](#issuecomment-1241086454)

Very interesting, kinda annoying the OpenAPI specification allows for this but it explains the `Vec<Option<String>>`
