### ISSUE TITLE
Reference variant should support description and summary fields.

### ISSUE THREAD

**Issue by naturalethic** [glademiller/openapiv3#69]
Currently the `Reference` variant of `ReferenceOr` only contains a `reference` string.  To accord with the spec, it should also include `description` and `status` fields.

**Comment by ahl** [comment]
Here's what I see in the spec:

https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00

> [7](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00#section-7).  Schema references with $ref
>    Any time a subschema is expected, a schema may instead use an object
>    containing a "$ref" property.  The value of the $ref is a URI
>    Reference.  Resolved against the current URI base, it identifies the
>    URI of a schema to use.  All other properties in a "$ref" object MUST
>    be ignored.
