### ISSUE TITLE
Schema extensions are not parsed

### ISSUE THREAD

**Issue by coriolinus** [glademiller/openapiv3#74]
It looks like schema extensions are not parsed, despite support existing in `SchemaData::extensions`.

@kurtbuilds this issue also affects `openapiv3-extended`, but that repo currently does not appear to have its issue tracker enabled.

## Example

```toml
[dependencies]
openapiv3 = "1.0.2"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
```

```yaml
openapi: "3.0.3"
info:
  version: "0.1.0"
  title: "Extension"
  description: |
    Extension properties are represented in the data model

paths: {}

components:
  schemas:
    Foo:
      type: object
      properties:
        qty_of_bar:
          type: integer
          name: count
          minimum: 0
```

```rust
use openapiv3::{OpenAPI, SchemaKind, Type};
use serde_json::Value;

#[test]
fn parses_extension() {
    let schema: OpenAPI = serde_yaml::from_str(SCHEMA).unwrap();
    let components = &schema.components.unwrap();
    let foo_schema = components.schemas.get("Foo").unwrap().as_item().unwrap();
    let SchemaKind::Type(Type::Object(foo_schema)) = &foo_schema.schema_kind else {
        panic!("wrong type");
    };
    let qty_bar_schema = foo_schema
        .properties
        .get("qty_of_bar")
        .unwrap()
        .as_item()
        .unwrap();
    let name = qty_bar_schema
        .schema_data
        .extensions
        .get("name")
        .and_then(Value::as_str);
    assert_eq!(name, Some("count"));
}
```

## Expected Outcome

The test passes: `count` gets parsed into the extensions field.

## Actual Outcome

The test fails; `name` is `None`.

```text
[src/main.rs:50] &qty_bar_schema = Schema {
    schema_data: SchemaData {
        nullable: false,
        read_only: false,
        write_only: false,
        deprecated: false,
        external_docs: None,
        example: None,
        title: None,
        description: None,
        discriminator: None,
        default: None,
        extensions: {},
    },
    schema_kind: Type(
        Integer(
            IntegerType {
                format: Empty,
                multiple_of: None,
                exclusive_minimum: false,
                exclusive_maximum: false,
                minimum: Some(
                    0,
                ),
                maximum: None,
                enumeration: [],
            },
        ),
    ),
}
```

**Comment by coriolinus** [comment]
Not a bug, it turns out: this library is intentionally filtering out extensions whose names do not begin with `x-`.

It would be very nice if the documentation explicitly mentioned that. Leaving this PR open as a feature request for such documentation.

**Comment by kurtbuilds** [comment]
Thanks for calling out that issues wasn't enabled. Turned that on.

@coriolinus Sounds like you found the issue. Good call on the doc string. I added a comment in `openapiv3-extended`, see https://github.com/kurtbuilds/openapiv3/commit/cb7946b35d3913369d9ca3ee3b97621557f016d8

Thought I'd offer for you to take a look and give feedback on the docs before cutting a patch release to update docs.rs.

**Comment by coriolinus** [comment]
That docs patch looks good to me. Thanks for getting it out quickly!

**Comment by ahl** [comment]
The spec generally requires extensions to start with `x-`. If you think this would be useful for the docs could you propose a doc PR? Note that extensions may appear in many places so I don't think it would suffice to put additional docs *only* in the SchemaData object.
