### ISSUE TITLE
new major version

### ISSUE THREAD

**Issue by ahl** [glademiller/openapiv3#81]
My intention is to release a new major version in the next week or so. In part this is because my handling of indexmap in #76 was... optimistic. In addition, I'm going to take the opportunity to roll in other breaking changes. I'll be doing an audit of issues and PRs. Feel free to comment on this issue if there are particular changes you'd like to see.

**Comment by ahl** [comment]
https://crates.io/crates/openapiv3/2.0.0-rc.1

**Comment by jayvdb** [comment]
Hi @ahl , are you aware that https://crates.io/crates/openapiv3/1.0.3 was yanked?

I dont see any CVE at https://osv.dev/list?ecosystem=crates.io&q=openapiv3

This means progenitor 0.4.0 is uninstallable, as it required 1.0.3 https://github.com/oxidecomputer/progenitor/blob/v0.4.0/progenitor-impl/Cargo.toml#L15

**Comment by ahl** [comment]
Thanks. I'll get a new release of progenitor cut soon.
