### ISSUE TITLE
data did not match any variant of untagged enum ReferenceOr

### ISSUE THREAD

**Issue by Poimen** [glademiller/openapiv3#85]
Hi,

I have an Open API spec that is 5MB big that NSwag produces for a C# gateway. I run this through a linter and most of the errors I get are around:
> a `$ref` cannot be placed next to any other properties

The NSwag output sample:
```json
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "nullable": false,
                  "$ref": "#/components/schemas/MessageCollection"
                }
              }
            }
          },
```

The OpenAPI is generated by a third party so no input in fixing this at the source.

When I run it through this crate, I get:
```
thread 'main' panicked at src/main.rs:6:55:
Could not deserialize input: Error("data did not match any variant of untagged enum ReferenceOr", line: 64510, column: 3)
```

I suspect it is the `$ref` with extra parameters involved.

Is there a way of making the parser/converter more lenient to non-conformances?

Thanks.

**Comment by ahl** [comment]
I believe you're right that this is due to `$ref` mixed with other content in a schema. Accommodating non-conformant data seems like a slippery slope. Could you post-process the OpenAPI document to transform constructions like that to

```json
                "schema": {
                  "nullable": false,
                  "allOf": [
                    "$ref": "#/components/schemas/MessageCollection"
                  ]
                }
```

Where did this OpenAPI document come from? Might the third party be amenable to changing how they generate the document?

**Comment by Poimen** [comment]
It's for internal web services, and "unfortunately" the redoc works fine, so they're unlikely to invest energy into fixing a schema. I would agree with you on the slippery slope, though.

I'll look at the pre-process before sending it in.

Thanks for the feedback 👍

**Comment by ahl** [comment]
Thanks for your understanding. I apologize for not being more flexible.

**Comment by Poimen** [comment]
Yup - no worries 😸 I appreciate the strictness of the cause, and wish all libraries could up hold the specification as highly.
