### ISSUE TITLE
Reponse.content should not be ReferenceOr

### ISSUE THREAD

**Issue by jesskfullwood** [glademiller/openapiv3#9]
Thanks for the lib.

According to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#response-object), I believe the `Response` object's `content` field should not be a `ReferenceOr<MediaType>` but just a bare `MediaType`.

**Comment by glademiller** [comment]
I believe you are correct about this. Would you mind creating a pull request?
